global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: go-sistem-baru
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["go-sistem-baru:3000"]
        labels:
          app: go-sistem-baru
          stack: qris

  - job_name: legacy-system-java
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["legacy-system-java:8081"]
        labels:
          app: legacy-system-java
          stack: qris

  - job_name: postgres
    scrape_interval: 15s
    static_configs:
      - targets: ["postgres-go-exporter:9187"]
        labels:
          app: go-sistem-baru
          database: qris_db
      - targets: ["postgres-legacy-exporter:9187"]
        labels:
          app: legacy-system-java
          database: qris_payment

  - job_name: redis
    scrape_interval: 15s
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          app: shared-redis

  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets: ["node-exporter:9100"]
