global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: qris-monitor

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: go-sistem-baru
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ["go-sistem-baru:3000"]
        labels:
          app: go-sistem-baru
          stack: qris
          environment: production

  - job_name: legacy-system-java
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ["legacy-system-java:8081"]
        labels:
          app: legacy-system-java
          stack: qris
          environment: production

  - job_name: postgres
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ["postgres-go-exporter:9187"]
        labels:
          app: go-sistem-baru
          database: qris_db
          environment: production
      - targets: ["postgres-legacy-exporter:9187"]
        labels:
          app: legacy-system-java
          database: qris_payment
          environment: production

  - job_name: redis
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          app: shared-redis
          environment: production

  - job_name: node-exporter
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          app: qris-host
          environment: production
